Repository AdobeDocs/commerce-admin.en, pull requests merged in 2022-09, with the labels that each got.

#7 remove MSI
  help/inventory-management/install-update.md
Labels: 2.4.x, major update

#8 ACP2E-1189: [Documentation] Add Bundle Product automatic status update rules into Bundle Product documentation
  help/catalog/product-create-bundle.md
Labels: minor update, 2.4.x, internal

#9 Fix list items on single line
  help/inventory-management/cli.md
Labels: 2.4.x, Editorial
